local skillz = T{};

skillz.wep_table = {
    [0] = 'None',
    [1] = 'HandToHand',
    [2] = 'Dagger',
    [3] = 'Sword',
    [4] = 'GreatSword',
    [5] = 'Axe',
    [6] = 'GreatAxe',
    [7] = 'Scythe',
    [8] ='Polearm',
    [9] ='Katana',
    [10] = 'GreatKatana',
    [11] = 'Club',
    [12] = 'Staff',
    [25] = 'Archery',
    [26] = 'Marksmanship',
};
skillz.wepSkills = { -- Weaponskills
    HandToHand = { --HandToHand
        ['Combo'] = {en='Combo',skillchain={'Impaction'}},
        ['Shoulder Tackle'] = {en='Shoulder Tackle',skillchain={'Reverberation','Impaction'}},
        ['One Inch Punch'] = {en='One Inch Punch',skillchain={'Compression'}},
        ['Backhand Blow'] = {en='Backhand Blow',skillchain={'Detonation'}},
        ['Raging Fists'] = {en='Raging Fists',skillchain={'Impaction'}},
        ['Spinning Attack'] = {en='Spinning Attack',skillchain={'Liquefaction','Impaction'}},
        ['Howling Fist'] = {en='Howling Fist',skillchain={'Transfixion','Impaction'}},
        ['Dragon Kick'] = {en='Dragon Kick',skillchain={'Fragmentation'}},
        ['Asuran Fists'] = {en='Asuran Fists',skillchain={'Gravitation','Liquefaction'}},
        ['Final Heaven'] = {en='Final Heaven',skillchain={'Light','Fusion'}},
    },
    Dagger = { --Dagger
        ['Wasp Sting'] = {en='Wasp Sting',skillchain={'Scission'}},
        ['Viper Bite'] = {en='Viper Bite',skillchain={'Scission'}},
        ['Shadowstitch'] = {en='Shadowstitch',skillchain={'Reverberation'}},
        ['Gust Slash'] = {en='Gust Slash',skillchain={'Detonation'}},
        ['Cyclone'] = {en='Cyclone',skillchain={'Detonation','Impaction'}},
        ['Dancing Edge'] = {en='Dancing Edge',skillchain={'Scission','Detonation'}},
        ['Shark Bite'] = {en='Shark Bite',skillchain={'Fragmentation'}},
        ['Evisceration'] = {en='Evisceration',skillchain={'Gravitation','Transfixion'}},
        ['Mercy Stroke'] = {en='Mercy Stroke',skillchain={'Darkness','Gravitation'}},
    },
    Sword ={    --Sword
        ['Fast Blade'] = {en='Fast Blade',skillchain={'Scission'}},
        ['Burning Blade'] = {en='Burning Blade',skillchain={'Liquefaction'}},
        ['Red Lotus Blade'] = {en='Red Lotus Blade',skillchain={'Liquefaction','Detonation'}},
        ['Flat Blade'] = {en='Flat Blade',skillchain={'Impaction'}},
        ['Shining Blade'] = {en='Shining Blade',skillchain={'Scission'}},
        ['Seraph Blade'] = {en='Seraph Blade',skillchain={'Scission','Transfixion'}},
        ['Circle Blade'] = {en='Circle Blade',skillchain={'Reverberation','Impaction'}},
        ['Vorpal Blade'] = {en='Vorpal Blade',skillchain={'Scission','Impaction'}},
        ['Swift Blade'] = {en='Swift Blade',skillchain={'Gravitation'}},
        ['Savage Blade'] = {en='Savage Blade',skillchain={'Fragmentation','Scission'}},
        ['Knights of Round'] = {en='Knights of Round',skillchain={'Light','Fusion'}},
    },
    GreatSword = {    --Great Sword
        ['Hard Slash'] = {en='Hard Slash',skillchain={'Scission'}},
        ['Power Slash'] = {en='Power Slash',skillchain={'Transfixion'}},
        ['Frostbite'] = {en='Frostbite',skillchain={'Induration'}},
        ['Freezebite'] = {en='Freezebite',skillchain={'Induration','Detonation'}},
        ['Shockwave'] = {en='Shockwave',skillchain={'Reverberation'}},
        ['Crescent Moon'] = {en='Crescent Moon',skillchain={'Scission'}},
        ['Sickle Moon'] = {en='Sickle Moon',skillchain={'Scission','Impaction'}},
        ['Spinning Slash'] = {en='Spinning Slash',skillchain={'Fragmentation'}},
        ['Ground Strike'] = {en='Ground Strike',skillchain={'Fragmentation','Distortion'}},
        ['Scourge'] = {en='Scourge',skillchain={'Light','Fusion'}},
    },
    Axe = {    --Axe
        ['Raging Axe'] = {en='Raging Axe',skillchain={'Detonation','Impaction'}},
        ['Smash Axe'] = {en='Smash Axe',skillchain={'Induration','Reverberation'}},
        ['Gale Axe'] = {en='Gale Axe',skillchain={'Detonation'}},
        ['Avalanche Axe'] = {en='Avalanche Axe',skillchain={'Induration'}},
        ['Spinning Axe'] = {en='Spinning Axe',skillchain={'Liquefaction','Scission','Impaction'}},
        ['Rampage'] = {en='Rampage',skillchain={'Scission'}},
        ['Calamity'] = {en='Calamity',skillchain={'Scission','Impaction'}},
        ['Mistral Axe'] = {en='Mistral Axe',skillchain={'Fusion'}},
        ['Decimation'] = {en='Decimation',skillchain={'Fusion','Detonation'}},
        ['Onslaught'] = {en='Onslaught',skillchain={'Darkness','Gravitation'}},
    },
    GreatAxe = { --Great Axe
        ['Shield Break'] = {en='Shield Break',skillchain={'Impaction'}},
        ['Iron Tempest'] = {en='Iron Tempest',skillchain={'Scission'}},
        ['Sturmwind'] = {en='Sturmwind',skillchain={'Reverberation','Scission'}},
        ['Armor Break'] = {en='Armor Break',skillchain={'Impaction'}},
        ['Keen Edge'] = {en='Keen Edge',skillchain={'Compression'}},
        ['Weapon Break'] = {en='Weapon Break',skillchain={'Impaction'}},
        ['Raging Rush'] = {en='Raging Rush',skillchain={'Induration','Reverberation'}},
        ['Full Break'] = {en='Full Break',skillchain={'Distortion'}},
        ['Steel Cyclone'] = {en='Steel Cyclone',skillchain={'Distortion','Detonation'}},
        ['Metatron Torment'] = {en='Metatron Torment',skillchain={'Light','Fusion'}},
    },
    Scythe = { --Scythe
        ['Slice'] = {en='Slice',skillchain={'Scission'}},
        ['Dark Harvest'] = {en='Dark Harvest',skillchain={'Reverberation'}},
        ['Shadow of Death'] = {en='Shadow of Death',skillchain={'Induration','Reverberation'}},
        ['Nightmare Scythe'] = {en='Nightmare Scythe',skillchain={'Compression','Scission'}},
        ['Spinning Scythe'] = {en='Spinning Scythe',skillchain={'Reverberation','Scission'}},
        ['Vorpal Scythe'] = {en='Vorpal Scythe',skillchain={'Transfixion','Scission'}},
        ['Guillotine'] = {en='Guillotine',skillchain={'Induration'}},
        ['Cross Reaper'] = {en='Cross Reaper',skillchain={'Distortion'}},
        ['Spiral Hell'] = {en='Spiral Hell',skillchain={'Distortion','Scission'}},
        ['Catastrophe'] = {en='Catastrophe',skillchain={'Fusion','Compression'}},
    },

    Polearm = {--Polearm
        ['Double Thrust'] = {en='Double Thrust',skillchain={'Transfixion'}},
        ['Thunder Thrust'] = {en='Thunder Thrust',skillchain={'Transfixion','Impaction'}},
        ['Raiden Thrust'] = {en='Raiden Thrust',skillchain={'Transfixion','Impaction'}},
        ['Leg Sweep'] = {en='Leg Sweep',skillchain={'Impaction'}},
        ['Penta Thrust'] = {en='Penta Thrust',skillchain={'Compression'}},
        ['Vorpal Thrust'] = {en='Vorpal Thrust',skillchain={'Reverberation','Transfixion'}},
        ['Skewer'] = {en='Skewer',skillchain={'Transfixion','Impaction'}},
        ['Wheeling Thrust'] = {en='Wheeling Thrust',skillchain={'Fusion'}},
        ['Impulse Drive'] = {en='Impulse Drive',skillchain={'Gravitation','Induration'}},
        ['Geirskogul'] = {en='Geirskogul',skillchain={'Light','Distortion'}},
    },
    Katana = { --Katana
        ['Blade: Rin'] = {en='Blade: Rin',skillchain={'Transfixion'}},
        ['Blade: Retsu'] = {en='Blade: Retsu',skillchain={'Scission'}},
        ['Blade: Teki'] = {en='Blade: Teki',skillchain={'Reverberation'}},
        ['Blade: To'] = {en='Blade: To',skillchain={'Induration','Detonation'}},
        ['Blade: Chi'] = {en='Blade: Chi',skillchain={'Transfixion','Impaction'}},
        ['Blade: Ei'] = {en='Blade: Ei',skillchain={'Compression'}},
        ['Blade: Jin'] = {en='Blade: Jin',skillchain={'Detonation','Impaction'}},
        ['Blade: Ten'] = {en='Blade: Ten',skillchain={'Gravitation'}},
        ['Blade: Ku'] = {en='Blade: Ku',skillchain={'Gravitation','Transfixion'}},
        ['Blade: Metsu'] = {en='Blade: Metsu',skillchain={'Darkness','Fragmentation'}},
    },
    GreatKatana = { --Great Katana
        ['Tachi: Enpi'] = {en='Tachi: Enpi',skillchain={'Transfixion','Scission'}},
        ['Tachi: Hobaku'] = {en='Tachi: Hobaku',skillchain={'Induration'}},
        ['Tachi: Goten'] = {en='Tachi: Goten',skillchain={'Transfixion','Impaction'}},
        ['Tachi: Kagero'] = {en='Tachi: Kagero',skillchain={'Liquefaction'}},
        ['Tachi: Jinpu'] = {en='Tachi: Jinpu',skillchain={'Scission','Detonation'}},
        ['Tachi: Koki'] = {en='Tachi: Koki',skillchain={'Reverberation','Impaction'}},
        ['Tachi: Yukikaze'] = {en='Tachi: Yukikaze',skillchain={'Induration','Detonation'}},
        ['Tachi: Gekko'] = {en='Tachi: Gekko',skillchain={'Distortion','Reverberation'}},
        ['Tachi: Kasha'] = {en='Tachi: Kasha',skillchain={'Fusion','Compression'}},
        ['Tachi: Kaiten'] = {en='Tachi: Kaiten',skillchain={'Light','Fragmentation'}},
    },
    Club = {    --Club
        ['Shining Strike'] = {en='Shining Strike',skillchain={'Transfixion'}},
        ['Seraph Strike'] = {en='Seraph Strike',skillchain={'Scission'}},
        ['Brainshaker'] = {en='Brainshaker',skillchain={'Reverberation'}},
        ['Skullbreaker'] = {en='Skullbreaker',skillchain={'Induration','Reverberation'}},
        ['True Strike'] = {en='True Strike',skillchain={'Detonation','Impaction'}},
        ['Judgment'] = {en='Judgment',skillchain={'Impaction'}},
        ['Hexa Strike'] = {en='Hexa Strike',skillchain={'Fusion'}},
        ['Black Halo'] = {en='Black Halo',skillchain={'Fragmentation','Compression'}},
        ['Randgrith'] = {en='Randgrith',skillchain={'Light','Fragmentation'}},
    },
    Staff = {--Staff
        ['Heavy Swing'] = {en='Heavy Swing',skillchain={'Impaction'}},
        ['Rock Crusher'] = {en='Rock Crusher',skillchain={'Impaction'}},
        ['Earth Crusher'] = {en='Earth Crusher',skillchain={'Detonation','Impaction'}},
        ['Starburst'] = {en='Starburst',skillchain={'Compression','Transfixion'}},
        ['Sunburst'] = {en='Sunburst',skillchain={'Transfixion','Reverberation'}},
        ['Shell Crusher'] = {en='Shell Crusher',skillchain={'Detonation'}},
        ['Full Swing'] = {en='Full Swing',skillchain={'Liquefaction','Impaction'}},
        ['Retribution'] = {en='Retribution',skillchain={'Gravitation','Reverberation'}},
        ['Gate of Tartarus'] = {en='Gate of Tartarus',skillchain={'Darkness','Distortion'}},
    },
    Archery = {    --Archery
        ['Flaming Arrow'] = {en='Flaming Arrow',skillchain={'Liquefaction','Transfixion'}},
        ['Piercing Arrow'] = {en='Piercing Arrow',skillchain={'Reverberation','Transfixion'}},
        ['Dulling Arrow'] = {en='Dulling Arrow',skillchain={'Liquefaction','Transfixion'}},
        ['Sidewinder'] = {en='Sidewinder',skillchain={'Reverberation','Transfixion','Detonation'}},
        ['Blast Arrow'] = {en='Blast Arrow',skillchain={'Induration','Transfixion'}},
        ['Arching Arrow'] = {en='Arching Arrow',skillchain={'Fusion'}},
        ['Empyreal Arrow'] = {en='Empyreal Arrow',skillchain={'Fusion','Transfixion'}},
        ['Namas Arrow'] = {en='Namas Arrow',skillchain={'Light','Distortion'}},
    },
    Marksmanship = {    --Marksmanship
        ['Hot Shot'] = {en='Hot Shot',skillchain={'Liquefaction','Transfixion'}},
        ['Split Shot'] = {en='Split Shot',skillchain={'Reverberation','Transfixion'}},
        ['Sniper Shot'] = {en='Sniper Shot',skillchain={'Liquefaction','Transfixion'}},
        ['Slug Shot'] = {en='Slug Shot',skillchain={'Reverberation','Transfixion','Detonation'}},
        ['Blast Shot'] = {en='Blast Shot',skillchain={'Induration','Transfixion'}},
        ['Heavy Shot'] = {en='Heavy Shot',skillchain={'Fusion'}},
        ['Detonator'] = {en='Detonator',skillchain={'Fusion','Transfixion'}},
        ['Coronach'] = {en='Coronach',skillchain={'Darkness','Fragmentation'}},
    },
};

return skillz